Allow to mimic the normal cli behavior of docker for docker_user
konstruktoid/ansible-docker-rootless pull request #13
Opened 2021-08-06 11:02 UTC by t2d

* Add new variable `docker_user_bashrc`, default false
* If true:
  * Manually download bash-completion
  * Deploy .bashrc for docker_user

Fix #12

2022-04-04 09:47 UTC, slhck commented
Any news on this? I think this would be nice to have. Seems this was auto-closed for being stale.

2022-04-04 10:47 UTC, konstruktoid commented
@t2d ?

2022-04-04 11:06 UTC, t2d commented
I had created an additional role since this wasn't merged. Anyhow, here is a rebased patch. Hope it suits your needs

2022-04-04 11:08 UTC, konstruktoid commented
It wasn't merged since none of my comments were addressed

2022-04-04 12:04 UTC, t2d commented
What comment is that? I only see https://github.com/konstruktoid/ansible-docker-rootless/issues/12#issuecomment-894145035 which is basically against this PR as a whole. Therefore, I didn't follow up. But really, no bad feelings from my side. Take whatever you like and throw the rest away. Thanks for the nice role.

2022-04-04 12:16 UTC, konstruktoid commented
I was referring to the review comments, but I'll have another look at the PR

![image](https://user-images.githubusercontent.com/7956715/161541584-c7cf840d-c096-45d0-9f90-f64fd50c6378.png)

2022-04-04 12:19 UTC, slhck commented
Have you submitted them? These comments look pending to me. There is no review open on this PR, actually.

FWIW, I would prefer to have these lines added to the `.bashrc` via a block managed by Ansible rather than completely overwriting the file. Otherwise this overwrites some OS defaults (part of `/etc/skel/.bashrc`).

2022-04-04 12:23 UTC, konstruktoid requested changes

2022-04-04 12:24 UTC, konstruktoid commented
> Have you submitted them? These comments look pending to me. There is no review open on this PR, actually.

Such fail from my side, sorry @t2d

2022-04-05 07:35 UTC, konstruktoid commented
Thanks for the updates @t2d

2022-04-05 07:36 UTC, konstruktoid approved these changes

2022-04-05 07:37 UTC, konstruktoid commented
I'll add a couple of test to this PR if that's ok.

2022-04-05 07:39 UTC, slhck commented on README.md
> +command will be place inside the `docker_user` home.
Minor nit: "placed"

2022-04-05 08:53 UTC, slhck commented
Cool, thanks for both of your time! 👍

2022-04-07 07:20 UTC, merged

2022-04-07 07:38 UTC, konstruktoid commented
merged.
and so sorry for the delay yet again.

will add tests during the day.